@startuml
'https://plantuml.com/sequence-diagram
title 会话设计
skinparam backgroundColor #EEEBDC
skinparam handwritten true
autonumber
participant 客户端 as client
participant 网关 as gateway
participant 账号服务 as account
participant 会话服务 as session
participant 持久层 as mysql
participant 缓存层 as redis

== 登录 ==
group login
client -> gateway : 登录请求
gateway -> account : 登录校验
alt succ
account -> gateway : true
gateway -> gateway:  绑定 UserContext 到 请求的 channel 下
end login
== 拉取上次会话 ==
group 获取会话
client -> gateway : 请求最近的会话
gateway -> session : 查询会话请求
session -> mysql : 拉取历史会话
group 拉取历史会话
mysql -> mysql : 账户下所有的session
mysql --> session : 回传 会话列表
session --> gateway : 回传 session
== 拉取历史消息 ==
client -> gateway: 查询 session 下的消息
note left :分页设计 查询近期100条
gateway -> session : query
seesion -> mysql : 查询数据信息
== 发送消息 ==
client -> gateway : msg




@enduml