@startuml
'https://plantuml.com/sequence-diagram
title  netty 业务串行业务的设计与实现
autonumber
actor 客户端 as client
Queue 客户端任务队列 as task
participant 服务端 as server
Queue 服务端任务队列 as serverTask
== request ==
group request
client ->  server : 提交业务请求
client ->task : 存放task 任务队列
note left : 生成 taskId 存入Task 队列等待
server -> server : accecpt request
server -> serverTask : IO操作提交用户级线程池处理
serverTask -> serverTask : io operate
end group
==  response ==
group response
serverTask --> server : work done respose
server -> client : 使用客户端的 协议header taskId\n加入response header 返回
client -> task : 解析header  根据taskId 在用户线程池处理业务 回调通知客户端业务方
end group

@enduml