// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Auth.proto

package com.ifx.connect.proto;

public final class Account {
  private Account() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AuthenticateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ifx.connect.proto.Authenticate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string jwt = 1;</code>
     * @return The jwt.
     */
    java.lang.String getJwt();
    /**
     * <code>string jwt = 1;</code>
     * @return The bytes for jwt.
     */
    com.google.protobuf.ByteString
        getJwtBytes();

    /**
     * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
     * @return Whether the accountInfo field is set.
     */
    boolean hasAccountInfo();
    /**
     * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
     * @return The accountInfo.
     */
    com.ifx.connect.proto.Account.AccountInfo getAccountInfo();
    /**
     * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
     */
    com.ifx.connect.proto.Account.AccountInfoOrBuilder getAccountInfoOrBuilder();
  }
  /**
   * Protobuf type {@code com.ifx.connect.proto.Authenticate}
   */
  public static final class Authenticate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ifx.connect.proto.Authenticate)
      AuthenticateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Authenticate.newBuilder() to construct.
    private Authenticate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Authenticate() {
      jwt_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Authenticate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Authenticate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              jwt_ = s;
              break;
            }
            case 18: {
              com.ifx.connect.proto.Account.AccountInfo.Builder subBuilder = null;
              if (accountInfo_ != null) {
                subBuilder = accountInfo_.toBuilder();
              }
              accountInfo_ = input.readMessage(com.ifx.connect.proto.Account.AccountInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(accountInfo_);
                accountInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ifx.connect.proto.Account.internal_static_com_ifx_connect_proto_Authenticate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ifx.connect.proto.Account.internal_static_com_ifx_connect_proto_Authenticate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ifx.connect.proto.Account.Authenticate.class, com.ifx.connect.proto.Account.Authenticate.Builder.class);
    }

    public static final int JWT_FIELD_NUMBER = 1;
    private volatile java.lang.Object jwt_;
    /**
     * <code>string jwt = 1;</code>
     * @return The jwt.
     */
    @java.lang.Override
    public java.lang.String getJwt() {
      java.lang.Object ref = jwt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jwt_ = s;
        return s;
      }
    }
    /**
     * <code>string jwt = 1;</code>
     * @return The bytes for jwt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJwtBytes() {
      java.lang.Object ref = jwt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jwt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNTINFO_FIELD_NUMBER = 2;
    private com.ifx.connect.proto.Account.AccountInfo accountInfo_;
    /**
     * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
     * @return Whether the accountInfo field is set.
     */
    @java.lang.Override
    public boolean hasAccountInfo() {
      return accountInfo_ != null;
    }
    /**
     * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
     * @return The accountInfo.
     */
    @java.lang.Override
    public com.ifx.connect.proto.Account.AccountInfo getAccountInfo() {
      return accountInfo_ == null ? com.ifx.connect.proto.Account.AccountInfo.getDefaultInstance() : accountInfo_;
    }
    /**
     * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
     */
    @java.lang.Override
    public com.ifx.connect.proto.Account.AccountInfoOrBuilder getAccountInfoOrBuilder() {
      return getAccountInfo();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getJwtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jwt_);
      }
      if (accountInfo_ != null) {
        output.writeMessage(2, getAccountInfo());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getJwtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jwt_);
      }
      if (accountInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getAccountInfo());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ifx.connect.proto.Account.Authenticate)) {
        return super.equals(obj);
      }
      com.ifx.connect.proto.Account.Authenticate other = (com.ifx.connect.proto.Account.Authenticate) obj;

      if (!getJwt()
          .equals(other.getJwt())) return false;
      if (hasAccountInfo() != other.hasAccountInfo()) return false;
      if (hasAccountInfo()) {
        if (!getAccountInfo()
            .equals(other.getAccountInfo())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JWT_FIELD_NUMBER;
      hash = (53 * hash) + getJwt().hashCode();
      if (hasAccountInfo()) {
        hash = (37 * hash) + ACCOUNTINFO_FIELD_NUMBER;
        hash = (53 * hash) + getAccountInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ifx.connect.proto.Account.Authenticate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ifx.connect.proto.Account.Authenticate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ifx.connect.proto.Account.Authenticate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ifx.connect.proto.Account.Authenticate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ifx.connect.proto.Account.Authenticate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ifx.connect.proto.Account.Authenticate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ifx.connect.proto.Account.Authenticate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ifx.connect.proto.Account.Authenticate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ifx.connect.proto.Account.Authenticate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ifx.connect.proto.Account.Authenticate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ifx.connect.proto.Account.Authenticate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ifx.connect.proto.Account.Authenticate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ifx.connect.proto.Account.Authenticate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ifx.connect.proto.Authenticate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ifx.connect.proto.Authenticate)
        com.ifx.connect.proto.Account.AuthenticateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ifx.connect.proto.Account.internal_static_com_ifx_connect_proto_Authenticate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ifx.connect.proto.Account.internal_static_com_ifx_connect_proto_Authenticate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ifx.connect.proto.Account.Authenticate.class, com.ifx.connect.proto.Account.Authenticate.Builder.class);
      }

      // Construct using com.ifx.connect.proto.Account.Authenticate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        jwt_ = "";

        if (accountInfoBuilder_ == null) {
          accountInfo_ = null;
        } else {
          accountInfo_ = null;
          accountInfoBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ifx.connect.proto.Account.internal_static_com_ifx_connect_proto_Authenticate_descriptor;
      }

      @java.lang.Override
      public com.ifx.connect.proto.Account.Authenticate getDefaultInstanceForType() {
        return com.ifx.connect.proto.Account.Authenticate.getDefaultInstance();
      }

      @java.lang.Override
      public com.ifx.connect.proto.Account.Authenticate build() {
        com.ifx.connect.proto.Account.Authenticate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ifx.connect.proto.Account.Authenticate buildPartial() {
        com.ifx.connect.proto.Account.Authenticate result = new com.ifx.connect.proto.Account.Authenticate(this);
        result.jwt_ = jwt_;
        if (accountInfoBuilder_ == null) {
          result.accountInfo_ = accountInfo_;
        } else {
          result.accountInfo_ = accountInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ifx.connect.proto.Account.Authenticate) {
          return mergeFrom((com.ifx.connect.proto.Account.Authenticate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ifx.connect.proto.Account.Authenticate other) {
        if (other == com.ifx.connect.proto.Account.Authenticate.getDefaultInstance()) return this;
        if (!other.getJwt().isEmpty()) {
          jwt_ = other.jwt_;
          onChanged();
        }
        if (other.hasAccountInfo()) {
          mergeAccountInfo(other.getAccountInfo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ifx.connect.proto.Account.Authenticate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ifx.connect.proto.Account.Authenticate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object jwt_ = "";
      /**
       * <code>string jwt = 1;</code>
       * @return The jwt.
       */
      public java.lang.String getJwt() {
        java.lang.Object ref = jwt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jwt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string jwt = 1;</code>
       * @return The bytes for jwt.
       */
      public com.google.protobuf.ByteString
          getJwtBytes() {
        java.lang.Object ref = jwt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jwt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string jwt = 1;</code>
       * @param value The jwt to set.
       * @return This builder for chaining.
       */
      public Builder setJwt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jwt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string jwt = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJwt() {
        
        jwt_ = getDefaultInstance().getJwt();
        onChanged();
        return this;
      }
      /**
       * <code>string jwt = 1;</code>
       * @param value The bytes for jwt to set.
       * @return This builder for chaining.
       */
      public Builder setJwtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jwt_ = value;
        onChanged();
        return this;
      }

      private com.ifx.connect.proto.Account.AccountInfo accountInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ifx.connect.proto.Account.AccountInfo, com.ifx.connect.proto.Account.AccountInfo.Builder, com.ifx.connect.proto.Account.AccountInfoOrBuilder> accountInfoBuilder_;
      /**
       * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
       * @return Whether the accountInfo field is set.
       */
      public boolean hasAccountInfo() {
        return accountInfoBuilder_ != null || accountInfo_ != null;
      }
      /**
       * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
       * @return The accountInfo.
       */
      public com.ifx.connect.proto.Account.AccountInfo getAccountInfo() {
        if (accountInfoBuilder_ == null) {
          return accountInfo_ == null ? com.ifx.connect.proto.Account.AccountInfo.getDefaultInstance() : accountInfo_;
        } else {
          return accountInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
       */
      public Builder setAccountInfo(com.ifx.connect.proto.Account.AccountInfo value) {
        if (accountInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          accountInfo_ = value;
          onChanged();
        } else {
          accountInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
       */
      public Builder setAccountInfo(
          com.ifx.connect.proto.Account.AccountInfo.Builder builderForValue) {
        if (accountInfoBuilder_ == null) {
          accountInfo_ = builderForValue.build();
          onChanged();
        } else {
          accountInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
       */
      public Builder mergeAccountInfo(com.ifx.connect.proto.Account.AccountInfo value) {
        if (accountInfoBuilder_ == null) {
          if (accountInfo_ != null) {
            accountInfo_ =
              com.ifx.connect.proto.Account.AccountInfo.newBuilder(accountInfo_).mergeFrom(value).buildPartial();
          } else {
            accountInfo_ = value;
          }
          onChanged();
        } else {
          accountInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
       */
      public Builder clearAccountInfo() {
        if (accountInfoBuilder_ == null) {
          accountInfo_ = null;
          onChanged();
        } else {
          accountInfo_ = null;
          accountInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
       */
      public com.ifx.connect.proto.Account.AccountInfo.Builder getAccountInfoBuilder() {
        
        onChanged();
        return getAccountInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
       */
      public com.ifx.connect.proto.Account.AccountInfoOrBuilder getAccountInfoOrBuilder() {
        if (accountInfoBuilder_ != null) {
          return accountInfoBuilder_.getMessageOrBuilder();
        } else {
          return accountInfo_ == null ?
              com.ifx.connect.proto.Account.AccountInfo.getDefaultInstance() : accountInfo_;
        }
      }
      /**
       * <code>.com.ifx.connect.proto.AccountInfo accountInfo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ifx.connect.proto.Account.AccountInfo, com.ifx.connect.proto.Account.AccountInfo.Builder, com.ifx.connect.proto.Account.AccountInfoOrBuilder> 
          getAccountInfoFieldBuilder() {
        if (accountInfoBuilder_ == null) {
          accountInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ifx.connect.proto.Account.AccountInfo, com.ifx.connect.proto.Account.AccountInfo.Builder, com.ifx.connect.proto.Account.AccountInfoOrBuilder>(
                  getAccountInfo(),
                  getParentForChildren(),
                  isClean());
          accountInfo_ = null;
        }
        return accountInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ifx.connect.proto.Authenticate)
    }

    // @@protoc_insertion_point(class_scope:com.ifx.connect.proto.Authenticate)
    private static final com.ifx.connect.proto.Account.Authenticate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ifx.connect.proto.Account.Authenticate();
    }

    public static com.ifx.connect.proto.Account.Authenticate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Authenticate>
        PARSER = new com.google.protobuf.AbstractParser<Authenticate>() {
      @java.lang.Override
      public Authenticate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Authenticate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Authenticate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Authenticate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ifx.connect.proto.Account.Authenticate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AccountInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ifx.connect.proto.AccountInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string account = 1;</code>
     * @return The account.
     */
    java.lang.String getAccount();
    /**
     * <code>string account = 1;</code>
     * @return The bytes for account.
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>string accountName = 2;</code>
     * @return The accountName.
     */
    java.lang.String getAccountName();
    /**
     * <code>string accountName = 2;</code>
     * @return The bytes for accountName.
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();

    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>string eMail = 4;</code>
     * @return The eMail.
     */
    java.lang.String getEMail();
    /**
     * <code>string eMail = 4;</code>
     * @return The bytes for eMail.
     */
    com.google.protobuf.ByteString
        getEMailBytes();
  }
  /**
   * Protobuf type {@code com.ifx.connect.proto.AccountInfo}
   */
  public static final class AccountInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ifx.connect.proto.AccountInfo)
      AccountInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AccountInfo.newBuilder() to construct.
    private AccountInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccountInfo() {
      account_ = "";
      accountName_ = "";
      eMail_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AccountInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AccountInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              accountName_ = s;
              break;
            }
            case 24: {

              userId_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              eMail_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ifx.connect.proto.Account.internal_static_com_ifx_connect_proto_AccountInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ifx.connect.proto.Account.internal_static_com_ifx_connect_proto_AccountInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ifx.connect.proto.Account.AccountInfo.class, com.ifx.connect.proto.Account.AccountInfo.Builder.class);
    }

    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private volatile java.lang.Object account_;
    /**
     * <code>string account = 1;</code>
     * @return The account.
     */
    @java.lang.Override
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>string account = 1;</code>
     * @return The bytes for account.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object accountName_;
    /**
     * <code>string accountName = 2;</code>
     * @return The accountName.
     */
    @java.lang.Override
    public java.lang.String getAccountName() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountName_ = s;
        return s;
      }
    }
    /**
     * <code>string accountName = 2;</code>
     * @return The bytes for accountName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private long userId_;
    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object eMail_;
    /**
     * <code>string eMail = 4;</code>
     * @return The eMail.
     */
    @java.lang.Override
    public java.lang.String getEMail() {
      java.lang.Object ref = eMail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eMail_ = s;
        return s;
      }
    }
    /**
     * <code>string eMail = 4;</code>
     * @return The bytes for eMail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEMailBytes() {
      java.lang.Object ref = eMail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eMail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, account_);
      }
      if (!getAccountNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accountName_);
      }
      if (userId_ != 0L) {
        output.writeInt64(3, userId_);
      }
      if (!getEMailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, eMail_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, account_);
      }
      if (!getAccountNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accountName_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, userId_);
      }
      if (!getEMailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, eMail_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ifx.connect.proto.Account.AccountInfo)) {
        return super.equals(obj);
      }
      com.ifx.connect.proto.Account.AccountInfo other = (com.ifx.connect.proto.Account.AccountInfo) obj;

      if (!getAccount()
          .equals(other.getAccount())) return false;
      if (!getAccountName()
          .equals(other.getAccountName())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getEMail()
          .equals(other.getEMail())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + ACCOUNTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getAccountName().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEMail().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ifx.connect.proto.Account.AccountInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ifx.connect.proto.Account.AccountInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ifx.connect.proto.Account.AccountInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ifx.connect.proto.Account.AccountInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ifx.connect.proto.Account.AccountInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ifx.connect.proto.Account.AccountInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ifx.connect.proto.Account.AccountInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ifx.connect.proto.Account.AccountInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ifx.connect.proto.Account.AccountInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ifx.connect.proto.Account.AccountInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ifx.connect.proto.Account.AccountInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ifx.connect.proto.Account.AccountInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ifx.connect.proto.Account.AccountInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ifx.connect.proto.AccountInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ifx.connect.proto.AccountInfo)
        com.ifx.connect.proto.Account.AccountInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ifx.connect.proto.Account.internal_static_com_ifx_connect_proto_AccountInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ifx.connect.proto.Account.internal_static_com_ifx_connect_proto_AccountInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ifx.connect.proto.Account.AccountInfo.class, com.ifx.connect.proto.Account.AccountInfo.Builder.class);
      }

      // Construct using com.ifx.connect.proto.Account.AccountInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        account_ = "";

        accountName_ = "";

        userId_ = 0L;

        eMail_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ifx.connect.proto.Account.internal_static_com_ifx_connect_proto_AccountInfo_descriptor;
      }

      @java.lang.Override
      public com.ifx.connect.proto.Account.AccountInfo getDefaultInstanceForType() {
        return com.ifx.connect.proto.Account.AccountInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.ifx.connect.proto.Account.AccountInfo build() {
        com.ifx.connect.proto.Account.AccountInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ifx.connect.proto.Account.AccountInfo buildPartial() {
        com.ifx.connect.proto.Account.AccountInfo result = new com.ifx.connect.proto.Account.AccountInfo(this);
        result.account_ = account_;
        result.accountName_ = accountName_;
        result.userId_ = userId_;
        result.eMail_ = eMail_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ifx.connect.proto.Account.AccountInfo) {
          return mergeFrom((com.ifx.connect.proto.Account.AccountInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ifx.connect.proto.Account.AccountInfo other) {
        if (other == com.ifx.connect.proto.Account.AccountInfo.getDefaultInstance()) return this;
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        if (!other.getAccountName().isEmpty()) {
          accountName_ = other.accountName_;
          onChanged();
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getEMail().isEmpty()) {
          eMail_ = other.eMail_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ifx.connect.proto.Account.AccountInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ifx.connect.proto.Account.AccountInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>string account = 1;</code>
       * @return The account.
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account = 1;</code>
       * @return The bytes for account.
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account = 1;</code>
       * @param value The account to set.
       * @return This builder for chaining.
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string account = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccount() {
        
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>string account = 1;</code>
       * @param value The bytes for account to set.
       * @return This builder for chaining.
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        account_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object accountName_ = "";
      /**
       * <code>string accountName = 2;</code>
       * @return The accountName.
       */
      public java.lang.String getAccountName() {
        java.lang.Object ref = accountName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string accountName = 2;</code>
       * @return The bytes for accountName.
       */
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        java.lang.Object ref = accountName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string accountName = 2;</code>
       * @param value The accountName to set.
       * @return This builder for chaining.
       */
      public Builder setAccountName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accountName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string accountName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountName() {
        
        accountName_ = getDefaultInstance().getAccountName();
        onChanged();
        return this;
      }
      /**
       * <code>string accountName = 2;</code>
       * @param value The bytes for accountName to set.
       * @return This builder for chaining.
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accountName_ = value;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 3;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 3;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object eMail_ = "";
      /**
       * <code>string eMail = 4;</code>
       * @return The eMail.
       */
      public java.lang.String getEMail() {
        java.lang.Object ref = eMail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eMail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string eMail = 4;</code>
       * @return The bytes for eMail.
       */
      public com.google.protobuf.ByteString
          getEMailBytes() {
        java.lang.Object ref = eMail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eMail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string eMail = 4;</code>
       * @param value The eMail to set.
       * @return This builder for chaining.
       */
      public Builder setEMail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eMail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string eMail = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEMail() {
        
        eMail_ = getDefaultInstance().getEMail();
        onChanged();
        return this;
      }
      /**
       * <code>string eMail = 4;</code>
       * @param value The bytes for eMail to set.
       * @return This builder for chaining.
       */
      public Builder setEMailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eMail_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ifx.connect.proto.AccountInfo)
    }

    // @@protoc_insertion_point(class_scope:com.ifx.connect.proto.AccountInfo)
    private static final com.ifx.connect.proto.Account.AccountInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ifx.connect.proto.Account.AccountInfo();
    }

    public static com.ifx.connect.proto.Account.AccountInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccountInfo>
        PARSER = new com.google.protobuf.AbstractParser<AccountInfo>() {
      @java.lang.Override
      public AccountInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccountInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AccountInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccountInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ifx.connect.proto.Account.AccountInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ifx_connect_proto_Authenticate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ifx_connect_proto_Authenticate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ifx_connect_proto_AccountInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ifx_connect_proto_AccountInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nAuth.proto\022\025com.ifx.connect.proto\"T\n\014A" +
      "uthenticate\022\013\n\003jwt\030\001 \001(\t\0227\n\013accountInfo\030" +
      "\002 \001(\0132\".com.ifx.connect.proto.AccountInf" +
      "o\"R\n\013AccountInfo\022\017\n\007account\030\001 \001(\t\022\023\n\013acc" +
      "ountName\030\002 \001(\t\022\016\n\006userId\030\003 \001(\003\022\r\n\005eMail\030" +
      "\004 \001(\tB \n\025com.ifx.connect.protoB\007Accountb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ifx_connect_proto_Authenticate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ifx_connect_proto_Authenticate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ifx_connect_proto_Authenticate_descriptor,
        new java.lang.String[] { "Jwt", "AccountInfo", });
    internal_static_com_ifx_connect_proto_AccountInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ifx_connect_proto_AccountInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ifx_connect_proto_AccountInfo_descriptor,
        new java.lang.String[] { "Account", "AccountName", "UserId", "EMail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
