// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.ifx.connect.proto;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ifx.connect.proto.ChatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * java-web-token
     * </pre>
     *
     * <code>string jwt = 2;</code>
     * @return The jwt.
     */
    java.lang.String getJwt();
    /**
     * <pre>
     * java-web-token
     * </pre>
     *
     * <code>string jwt = 2;</code>
     * @return The bytes for jwt.
     */
    com.google.protobuf.ByteString
        getJwtBytes();

    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>string fromAccount = 5;</code>
     * @return The fromAccount.
     */
    java.lang.String getFromAccount();
    /**
     * <code>string fromAccount = 5;</code>
     * @return The bytes for fromAccount.
     */
    com.google.protobuf.ByteString
        getFromAccountBytes();

    /**
     * <code>string toAccount = 6;</code>
     * @return The toAccount.
     */
    java.lang.String getToAccount();
    /**
     * <code>string toAccount = 6;</code>
     * @return The bytes for toAccount.
     */
    com.google.protobuf.ByteString
        getToAccountBytes();

    /**
     * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
     * @return Whether the j3 field is set.
     */
    boolean hasJ3();
    /**
     * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
     * @return The j3.
     */
    com.ifx.connect.proto.ProtoMessage.ProtocolHeader getJ3();
    /**
     * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
     */
    com.ifx.connect.proto.ProtoMessage.ProtocolHeaderOrBuilder getJ3OrBuilder();

    /**
     * <code>.com.ifx.connect.proto.ProtocolMessageEnum en = 8;</code>
     * @return The enum numeric value on the wire for en.
     */
    int getEnValue();
    /**
     * <code>.com.ifx.connect.proto.ProtocolMessageEnum en = 8;</code>
     * @return The en.
     */
    com.ifx.connect.proto.ProtocolMessage.ProtocolMessageEnum getEn();
  }
  /**
   * Protobuf type {@code com.ifx.connect.proto.ChatMessage}
   */
  public static final class ChatMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ifx.connect.proto.ChatMessage)
      ChatMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatMessage.newBuilder() to construct.
    private ChatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMessage() {
      jwt_ = "";
      content_ = "";
      fromAccount_ = "";
      toAccount_ = "";
      en_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ifx.connect.proto.Chat.internal_static_com_ifx_connect_proto_ChatMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ifx.connect.proto.Chat.internal_static_com_ifx_connect_proto_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ifx.connect.proto.Chat.ChatMessage.class, com.ifx.connect.proto.Chat.ChatMessage.Builder.class);
    }

    public static final int JWT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object jwt_ = "";
    /**
     * <pre>
     * java-web-token
     * </pre>
     *
     * <code>string jwt = 2;</code>
     * @return The jwt.
     */
    @java.lang.Override
    public java.lang.String getJwt() {
      java.lang.Object ref = jwt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jwt_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * java-web-token
     * </pre>
     *
     * <code>string jwt = 2;</code>
     * @return The bytes for jwt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJwtBytes() {
      java.lang.Object ref = jwt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jwt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object content_ = "";
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMACCOUNT_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fromAccount_ = "";
    /**
     * <code>string fromAccount = 5;</code>
     * @return The fromAccount.
     */
    @java.lang.Override
    public java.lang.String getFromAccount() {
      java.lang.Object ref = fromAccount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromAccount_ = s;
        return s;
      }
    }
    /**
     * <code>string fromAccount = 5;</code>
     * @return The bytes for fromAccount.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromAccountBytes() {
      java.lang.Object ref = fromAccount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOACCOUNT_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object toAccount_ = "";
    /**
     * <code>string toAccount = 6;</code>
     * @return The toAccount.
     */
    @java.lang.Override
    public java.lang.String getToAccount() {
      java.lang.Object ref = toAccount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toAccount_ = s;
        return s;
      }
    }
    /**
     * <code>string toAccount = 6;</code>
     * @return The bytes for toAccount.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToAccountBytes() {
      java.lang.Object ref = toAccount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int J3_FIELD_NUMBER = 4;
    private com.ifx.connect.proto.ProtoMessage.ProtocolHeader j3_;
    /**
     * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
     * @return Whether the j3 field is set.
     */
    @java.lang.Override
    public boolean hasJ3() {
      return j3_ != null;
    }
    /**
     * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
     * @return The j3.
     */
    @java.lang.Override
    public com.ifx.connect.proto.ProtoMessage.ProtocolHeader getJ3() {
      return j3_ == null ? com.ifx.connect.proto.ProtoMessage.ProtocolHeader.getDefaultInstance() : j3_;
    }
    /**
     * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
     */
    @java.lang.Override
    public com.ifx.connect.proto.ProtoMessage.ProtocolHeaderOrBuilder getJ3OrBuilder() {
      return j3_ == null ? com.ifx.connect.proto.ProtoMessage.ProtocolHeader.getDefaultInstance() : j3_;
    }

    public static final int EN_FIELD_NUMBER = 8;
    private int en_ = 0;
    /**
     * <code>.com.ifx.connect.proto.ProtocolMessageEnum en = 8;</code>
     * @return The enum numeric value on the wire for en.
     */
    @java.lang.Override public int getEnValue() {
      return en_;
    }
    /**
     * <code>.com.ifx.connect.proto.ProtocolMessageEnum en = 8;</code>
     * @return The en.
     */
    @java.lang.Override public com.ifx.connect.proto.ProtocolMessage.ProtocolMessageEnum getEn() {
      com.ifx.connect.proto.ProtocolMessage.ProtocolMessageEnum result = com.ifx.connect.proto.ProtocolMessage.ProtocolMessageEnum.forNumber(en_);
      return result == null ? com.ifx.connect.proto.ProtocolMessage.ProtocolMessageEnum.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jwt_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, jwt_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (j3_ != null) {
        output.writeMessage(4, getJ3());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromAccount_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fromAccount_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toAccount_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, toAccount_);
      }
      if (en_ != com.ifx.connect.proto.ProtocolMessage.ProtocolMessageEnum.TMP.getNumber()) {
        output.writeEnum(8, en_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jwt_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, jwt_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (j3_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getJ3());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromAccount_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, fromAccount_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toAccount_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, toAccount_);
      }
      if (en_ != com.ifx.connect.proto.ProtocolMessage.ProtocolMessageEnum.TMP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, en_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ifx.connect.proto.Chat.ChatMessage)) {
        return super.equals(obj);
      }
      com.ifx.connect.proto.Chat.ChatMessage other = (com.ifx.connect.proto.Chat.ChatMessage) obj;

      if (!getJwt()
          .equals(other.getJwt())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getFromAccount()
          .equals(other.getFromAccount())) return false;
      if (!getToAccount()
          .equals(other.getToAccount())) return false;
      if (hasJ3() != other.hasJ3()) return false;
      if (hasJ3()) {
        if (!getJ3()
            .equals(other.getJ3())) return false;
      }
      if (en_ != other.en_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JWT_FIELD_NUMBER;
      hash = (53 * hash) + getJwt().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + FROMACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getFromAccount().hashCode();
      hash = (37 * hash) + TOACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getToAccount().hashCode();
      if (hasJ3()) {
        hash = (37 * hash) + J3_FIELD_NUMBER;
        hash = (53 * hash) + getJ3().hashCode();
      }
      hash = (37 * hash) + EN_FIELD_NUMBER;
      hash = (53 * hash) + en_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ifx.connect.proto.Chat.ChatMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ifx.connect.proto.Chat.ChatMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ifx.connect.proto.Chat.ChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ifx.connect.proto.Chat.ChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ifx.connect.proto.Chat.ChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ifx.connect.proto.Chat.ChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ifx.connect.proto.Chat.ChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ifx.connect.proto.Chat.ChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ifx.connect.proto.Chat.ChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ifx.connect.proto.Chat.ChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ifx.connect.proto.Chat.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ifx.connect.proto.Chat.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ifx.connect.proto.Chat.ChatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ifx.connect.proto.ChatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ifx.connect.proto.ChatMessage)
        com.ifx.connect.proto.Chat.ChatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ifx.connect.proto.Chat.internal_static_com_ifx_connect_proto_ChatMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ifx.connect.proto.Chat.internal_static_com_ifx_connect_proto_ChatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ifx.connect.proto.Chat.ChatMessage.class, com.ifx.connect.proto.Chat.ChatMessage.Builder.class);
      }

      // Construct using com.ifx.connect.proto.Chat.ChatMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        jwt_ = "";
        content_ = "";
        fromAccount_ = "";
        toAccount_ = "";
        j3_ = null;
        if (j3Builder_ != null) {
          j3Builder_.dispose();
          j3Builder_ = null;
        }
        en_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ifx.connect.proto.Chat.internal_static_com_ifx_connect_proto_ChatMessage_descriptor;
      }

      @java.lang.Override
      public com.ifx.connect.proto.Chat.ChatMessage getDefaultInstanceForType() {
        return com.ifx.connect.proto.Chat.ChatMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.ifx.connect.proto.Chat.ChatMessage build() {
        com.ifx.connect.proto.Chat.ChatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ifx.connect.proto.Chat.ChatMessage buildPartial() {
        com.ifx.connect.proto.Chat.ChatMessage result = new com.ifx.connect.proto.Chat.ChatMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.ifx.connect.proto.Chat.ChatMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.jwt_ = jwt_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.fromAccount_ = fromAccount_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.toAccount_ = toAccount_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.j3_ = j3Builder_ == null
              ? j3_
              : j3Builder_.build();
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.en_ = en_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ifx.connect.proto.Chat.ChatMessage) {
          return mergeFrom((com.ifx.connect.proto.Chat.ChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ifx.connect.proto.Chat.ChatMessage other) {
        if (other == com.ifx.connect.proto.Chat.ChatMessage.getDefaultInstance()) return this;
        if (!other.getJwt().isEmpty()) {
          jwt_ = other.jwt_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getFromAccount().isEmpty()) {
          fromAccount_ = other.fromAccount_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getToAccount().isEmpty()) {
          toAccount_ = other.toAccount_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasJ3()) {
          mergeJ3(other.getJ3());
        }
        if (other.en_ != 0) {
          setEnValue(other.getEnValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {
                jwt_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 18
              case 26: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getJ3FieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 34
              case 42: {
                fromAccount_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 42
              case 50: {
                toAccount_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 50
              case 64: {
                en_ = input.readEnum();
                bitField0_ |= 0x00000020;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object jwt_ = "";
      /**
       * <pre>
       * java-web-token
       * </pre>
       *
       * <code>string jwt = 2;</code>
       * @return The jwt.
       */
      public java.lang.String getJwt() {
        java.lang.Object ref = jwt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jwt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * java-web-token
       * </pre>
       *
       * <code>string jwt = 2;</code>
       * @return The bytes for jwt.
       */
      public com.google.protobuf.ByteString
          getJwtBytes() {
        java.lang.Object ref = jwt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jwt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * java-web-token
       * </pre>
       *
       * <code>string jwt = 2;</code>
       * @param value The jwt to set.
       * @return This builder for chaining.
       */
      public Builder setJwt(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        jwt_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * java-web-token
       * </pre>
       *
       * <code>string jwt = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearJwt() {
        jwt_ = getDefaultInstance().getJwt();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * java-web-token
       * </pre>
       *
       * <code>string jwt = 2;</code>
       * @param value The bytes for jwt to set.
       * @return This builder for chaining.
       */
      public Builder setJwtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        jwt_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 3;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object fromAccount_ = "";
      /**
       * <code>string fromAccount = 5;</code>
       * @return The fromAccount.
       */
      public java.lang.String getFromAccount() {
        java.lang.Object ref = fromAccount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromAccount_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fromAccount = 5;</code>
       * @return The bytes for fromAccount.
       */
      public com.google.protobuf.ByteString
          getFromAccountBytes() {
        java.lang.Object ref = fromAccount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromAccount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fromAccount = 5;</code>
       * @param value The fromAccount to set.
       * @return This builder for chaining.
       */
      public Builder setFromAccount(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fromAccount_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string fromAccount = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromAccount() {
        fromAccount_ = getDefaultInstance().getFromAccount();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string fromAccount = 5;</code>
       * @param value The bytes for fromAccount to set.
       * @return This builder for chaining.
       */
      public Builder setFromAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fromAccount_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object toAccount_ = "";
      /**
       * <code>string toAccount = 6;</code>
       * @return The toAccount.
       */
      public java.lang.String getToAccount() {
        java.lang.Object ref = toAccount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toAccount_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string toAccount = 6;</code>
       * @return The bytes for toAccount.
       */
      public com.google.protobuf.ByteString
          getToAccountBytes() {
        java.lang.Object ref = toAccount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toAccount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string toAccount = 6;</code>
       * @param value The toAccount to set.
       * @return This builder for chaining.
       */
      public Builder setToAccount(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        toAccount_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string toAccount = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearToAccount() {
        toAccount_ = getDefaultInstance().getToAccount();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string toAccount = 6;</code>
       * @param value The bytes for toAccount to set.
       * @return This builder for chaining.
       */
      public Builder setToAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        toAccount_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.ifx.connect.proto.ProtoMessage.ProtocolHeader j3_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ifx.connect.proto.ProtoMessage.ProtocolHeader, com.ifx.connect.proto.ProtoMessage.ProtocolHeader.Builder, com.ifx.connect.proto.ProtoMessage.ProtocolHeaderOrBuilder> j3Builder_;
      /**
       * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
       * @return Whether the j3 field is set.
       */
      public boolean hasJ3() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
       * @return The j3.
       */
      public com.ifx.connect.proto.ProtoMessage.ProtocolHeader getJ3() {
        if (j3Builder_ == null) {
          return j3_ == null ? com.ifx.connect.proto.ProtoMessage.ProtocolHeader.getDefaultInstance() : j3_;
        } else {
          return j3Builder_.getMessage();
        }
      }
      /**
       * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
       */
      public Builder setJ3(com.ifx.connect.proto.ProtoMessage.ProtocolHeader value) {
        if (j3Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          j3_ = value;
        } else {
          j3Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
       */
      public Builder setJ3(
          com.ifx.connect.proto.ProtoMessage.ProtocolHeader.Builder builderForValue) {
        if (j3Builder_ == null) {
          j3_ = builderForValue.build();
        } else {
          j3Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
       */
      public Builder mergeJ3(com.ifx.connect.proto.ProtoMessage.ProtocolHeader value) {
        if (j3Builder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            j3_ != null &&
            j3_ != com.ifx.connect.proto.ProtoMessage.ProtocolHeader.getDefaultInstance()) {
            getJ3Builder().mergeFrom(value);
          } else {
            j3_ = value;
          }
        } else {
          j3Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
       */
      public Builder clearJ3() {
        bitField0_ = (bitField0_ & ~0x00000010);
        j3_ = null;
        if (j3Builder_ != null) {
          j3Builder_.dispose();
          j3Builder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
       */
      public com.ifx.connect.proto.ProtoMessage.ProtocolHeader.Builder getJ3Builder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getJ3FieldBuilder().getBuilder();
      }
      /**
       * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
       */
      public com.ifx.connect.proto.ProtoMessage.ProtocolHeaderOrBuilder getJ3OrBuilder() {
        if (j3Builder_ != null) {
          return j3Builder_.getMessageOrBuilder();
        } else {
          return j3_ == null ?
              com.ifx.connect.proto.ProtoMessage.ProtocolHeader.getDefaultInstance() : j3_;
        }
      }
      /**
       * <code>.com.ifx.connect.proto.ProtocolHeader j3 = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ifx.connect.proto.ProtoMessage.ProtocolHeader, com.ifx.connect.proto.ProtoMessage.ProtocolHeader.Builder, com.ifx.connect.proto.ProtoMessage.ProtocolHeaderOrBuilder> 
          getJ3FieldBuilder() {
        if (j3Builder_ == null) {
          j3Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ifx.connect.proto.ProtoMessage.ProtocolHeader, com.ifx.connect.proto.ProtoMessage.ProtocolHeader.Builder, com.ifx.connect.proto.ProtoMessage.ProtocolHeaderOrBuilder>(
                  getJ3(),
                  getParentForChildren(),
                  isClean());
          j3_ = null;
        }
        return j3Builder_;
      }

      private int en_ = 0;
      /**
       * <code>.com.ifx.connect.proto.ProtocolMessageEnum en = 8;</code>
       * @return The enum numeric value on the wire for en.
       */
      @java.lang.Override public int getEnValue() {
        return en_;
      }
      /**
       * <code>.com.ifx.connect.proto.ProtocolMessageEnum en = 8;</code>
       * @param value The enum numeric value on the wire for en to set.
       * @return This builder for chaining.
       */
      public Builder setEnValue(int value) {
        en_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.com.ifx.connect.proto.ProtocolMessageEnum en = 8;</code>
       * @return The en.
       */
      @java.lang.Override
      public com.ifx.connect.proto.ProtocolMessage.ProtocolMessageEnum getEn() {
        com.ifx.connect.proto.ProtocolMessage.ProtocolMessageEnum result = com.ifx.connect.proto.ProtocolMessage.ProtocolMessageEnum.forNumber(en_);
        return result == null ? com.ifx.connect.proto.ProtocolMessage.ProtocolMessageEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.ifx.connect.proto.ProtocolMessageEnum en = 8;</code>
       * @param value The en to set.
       * @return This builder for chaining.
       */
      public Builder setEn(com.ifx.connect.proto.ProtocolMessage.ProtocolMessageEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        en_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.ifx.connect.proto.ProtocolMessageEnum en = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearEn() {
        bitField0_ = (bitField0_ & ~0x00000020);
        en_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ifx.connect.proto.ChatMessage)
    }

    // @@protoc_insertion_point(class_scope:com.ifx.connect.proto.ChatMessage)
    private static final com.ifx.connect.proto.Chat.ChatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ifx.connect.proto.Chat.ChatMessage();
    }

    public static com.ifx.connect.proto.Chat.ChatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMessage>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
      @java.lang.Override
      public ChatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChatMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ifx.connect.proto.Chat.ChatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ifx_connect_proto_ChatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ifx_connect_proto_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\025com.ifx.connect.proto\032\024" +
      "ActionProtocol.proto\032\021MessageEnum.proto\032" +
      "\031google/protobuf/any.proto\"\276\001\n\013ChatMessa" +
      "ge\022\013\n\003jwt\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\022\023\n\013from" +
      "Account\030\005 \001(\t\022\021\n\ttoAccount\030\006 \001(\t\0221\n\002j3\030\004" +
      " \001(\0132%.com.ifx.connect.proto.ProtocolHea" +
      "der\0226\n\002en\030\010 \001(\0162*.com.ifx.connect.proto." +
      "ProtocolMessageEnumB\035\n\025com.ifx.connect.p" +
      "rotoB\004Chatb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ifx.connect.proto.ProtoMessage.getDescriptor(),
          com.ifx.connect.proto.ProtocolMessage.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_com_ifx_connect_proto_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ifx_connect_proto_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ifx_connect_proto_ChatMessage_descriptor,
        new java.lang.String[] { "Jwt", "Content", "FromAccount", "ToAccount", "J3", "En", });
    com.ifx.connect.proto.ProtoMessage.getDescriptor();
    com.ifx.connect.proto.ProtocolMessage.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
