// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageEnum.proto

package com.ifx.connect.proto;

public final class ProtocolType {
  private ProtocolType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.ifx.connect.proto.ProtocolMessageEnum}
   */
  public enum ProtocolMessageEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TMP = 0;</code>
     */
    TMP(0),
    /**
     * <code>AUTH = 1001;</code>
     */
    AUTH(1001),
    /**
     * <code>CHAT = 1002;</code>
     */
    CHAT(1002),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TMP = 0;</code>
     */
    public static final int TMP_VALUE = 0;
    /**
     * <code>AUTH = 1001;</code>
     */
    public static final int AUTH_VALUE = 1001;
    /**
     * <code>CHAT = 1002;</code>
     */
    public static final int CHAT_VALUE = 1002;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProtocolMessageEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ProtocolMessageEnum forNumber(int value) {
      switch (value) {
        case 0: return TMP;
        case 1001: return AUTH;
        case 1002: return CHAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtocolMessageEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtocolMessageEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtocolMessageEnum>() {
            public ProtocolMessageEnum findValueByNumber(int number) {
              return ProtocolMessageEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ifx.connect.proto.ProtocolType.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtocolMessageEnum[] VALUES = values();

    public static ProtocolMessageEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProtocolMessageEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ifx.connect.proto.ProtocolMessageEnum)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MessageEnum.proto\022\025com.ifx.connect.pro" +
      "to*4\n\023ProtocolMessageEnum\022\007\n\003TMP\020\000\022\t\n\004AU" +
      "TH\020\351\007\022\t\n\004CHAT\020\352\007B%\n\025com.ifx.connect.prot" +
      "oB\014ProtocolTypeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
