// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ActionProtocol.proto

package com.ifx.connect.proto;

public final class ProtoMessage {
  private ProtoMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtocolHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ifx.connect.proto.ProtocolHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 mes = 1;</code>
     * @return The mes.
     */
    int getMes();
  }
  /**
   * <pre>
   *base protocol header
   * </pre>
   *
   * Protobuf type {@code com.ifx.connect.proto.ProtocolHeader}
   */
  public static final class ProtocolHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ifx.connect.proto.ProtocolHeader)
      ProtocolHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtocolHeader.newBuilder() to construct.
    private ProtocolHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtocolHeader() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtocolHeader();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ifx.connect.proto.ProtoMessage.internal_static_com_ifx_connect_proto_ProtocolHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ifx.connect.proto.ProtoMessage.internal_static_com_ifx_connect_proto_ProtocolHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ifx.connect.proto.ProtoMessage.ProtocolHeader.class, com.ifx.connect.proto.ProtoMessage.ProtocolHeader.Builder.class);
    }

    public static final int MES_FIELD_NUMBER = 1;
    private int mes_ = 0;
    /**
     * <code>int32 mes = 1;</code>
     * @return The mes.
     */
    @java.lang.Override
    public int getMes() {
      return mes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mes_ != 0) {
        output.writeInt32(1, mes_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ifx.connect.proto.ProtoMessage.ProtocolHeader)) {
        return super.equals(obj);
      }
      com.ifx.connect.proto.ProtoMessage.ProtocolHeader other = (com.ifx.connect.proto.ProtoMessage.ProtocolHeader) obj;

      if (getMes()
          != other.getMes()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MES_FIELD_NUMBER;
      hash = (53 * hash) + getMes();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ifx.connect.proto.ProtoMessage.ProtocolHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ifx.connect.proto.ProtoMessage.ProtocolHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ifx.connect.proto.ProtoMessage.ProtocolHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ifx.connect.proto.ProtoMessage.ProtocolHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ifx.connect.proto.ProtoMessage.ProtocolHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ifx.connect.proto.ProtoMessage.ProtocolHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ifx.connect.proto.ProtoMessage.ProtocolHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ifx.connect.proto.ProtoMessage.ProtocolHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ifx.connect.proto.ProtoMessage.ProtocolHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ifx.connect.proto.ProtoMessage.ProtocolHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ifx.connect.proto.ProtoMessage.ProtocolHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ifx.connect.proto.ProtoMessage.ProtocolHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ifx.connect.proto.ProtoMessage.ProtocolHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *base protocol header
     * </pre>
     *
     * Protobuf type {@code com.ifx.connect.proto.ProtocolHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ifx.connect.proto.ProtocolHeader)
        com.ifx.connect.proto.ProtoMessage.ProtocolHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ifx.connect.proto.ProtoMessage.internal_static_com_ifx_connect_proto_ProtocolHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ifx.connect.proto.ProtoMessage.internal_static_com_ifx_connect_proto_ProtocolHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ifx.connect.proto.ProtoMessage.ProtocolHeader.class, com.ifx.connect.proto.ProtoMessage.ProtocolHeader.Builder.class);
      }

      // Construct using com.ifx.connect.proto.ProtoMessage.ProtocolHeader.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        mes_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ifx.connect.proto.ProtoMessage.internal_static_com_ifx_connect_proto_ProtocolHeader_descriptor;
      }

      @java.lang.Override
      public com.ifx.connect.proto.ProtoMessage.ProtocolHeader getDefaultInstanceForType() {
        return com.ifx.connect.proto.ProtoMessage.ProtocolHeader.getDefaultInstance();
      }

      @java.lang.Override
      public com.ifx.connect.proto.ProtoMessage.ProtocolHeader build() {
        com.ifx.connect.proto.ProtoMessage.ProtocolHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ifx.connect.proto.ProtoMessage.ProtocolHeader buildPartial() {
        com.ifx.connect.proto.ProtoMessage.ProtocolHeader result = new com.ifx.connect.proto.ProtoMessage.ProtocolHeader(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.ifx.connect.proto.ProtoMessage.ProtocolHeader result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.mes_ = mes_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ifx.connect.proto.ProtoMessage.ProtocolHeader) {
          return mergeFrom((com.ifx.connect.proto.ProtoMessage.ProtocolHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ifx.connect.proto.ProtoMessage.ProtocolHeader other) {
        if (other == com.ifx.connect.proto.ProtoMessage.ProtocolHeader.getDefaultInstance()) return this;
        if (other.getMes() != 0) {
          setMes(other.getMes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                mes_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int mes_ ;
      /**
       * <code>int32 mes = 1;</code>
       * @return The mes.
       */
      @java.lang.Override
      public int getMes() {
        return mes_;
      }
      /**
       * <code>int32 mes = 1;</code>
       * @param value The mes to set.
       * @return This builder for chaining.
       */
      public Builder setMes(int value) {

        mes_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 mes = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mes_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ifx.connect.proto.ProtocolHeader)
    }

    // @@protoc_insertion_point(class_scope:com.ifx.connect.proto.ProtocolHeader)
    private static final com.ifx.connect.proto.ProtoMessage.ProtocolHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ifx.connect.proto.ProtoMessage.ProtocolHeader();
    }

    public static com.ifx.connect.proto.ProtoMessage.ProtocolHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtocolHeader>
        PARSER = new com.google.protobuf.AbstractParser<ProtocolHeader>() {
      @java.lang.Override
      public ProtocolHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProtocolHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtocolHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ifx.connect.proto.ProtoMessage.ProtocolHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ifx_connect_proto_ProtocolHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ifx_connect_proto_ProtocolHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ActionProtocol.proto\022\025com.ifx.connect." +
      "proto\"\035\n\016ProtocolHeader\022\013\n\003mes\030\001 \001(\005B%\n\025" +
      "com.ifx.connect.protoB\014ProtoMessageb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ifx_connect_proto_ProtocolHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ifx_connect_proto_ProtocolHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ifx_connect_proto_ProtocolHeader_descriptor,
        new java.lang.String[] { "Mes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
